apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: datanode1
  name: datanode1
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 9864
    protocol: TCP
    targetPort: 9864
  selector:
    app: datanode1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}