apiVersion: v1
kind: Service
metadata:
  name: driver-lb
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    app: driver-gui
  sessionAffinity: None
  type: LoadBalancer